services:
  app:
    build:
      context: .
    env_file: env/env.develop
    restart: unless-stopped
    depends_on:
      pg:
        condition: service_healthy

  pg:
    image: postgres:17
    env_file: ./env/env.pg
    volumes:
      - pg-data:/var/lib/postgresql/data
    restart: unless-stopped
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pg-data: