spring:
  application:
    name: "api"
  datasource:
    url: jdbc:postgresql://localhost:5432/${DB_NAME:autoappdb}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:secret}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect

server:
  port: ${APP_PORT:9999}

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
